export default {
  wrap: {
    outer: {
      display: 'table',
      position: 'fixed',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      minWidth: '1vw',
      minHeight: '1vh',
      backgroundColor: 'rgba(0,0,0,0.5)',
      overflow: 'hidden',
      margin: 0,
      border: 0,
      padding: 0,
    },
    inner: {
      display: 'table-cell',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      verticalAlign: 'middle',
      margin: 0,
      border: 0,
      padding: 0,
    },
    inner2: {
      position: 'relative',
      width: '100%',
      maxHeight: '100%',
      display: 'inline-block',
      overflow: 'auto',
      textAlign: 'center',
      margin: 0,
      border: 0,
      padding: 0,
    },
  },
  choose: {
    marginTop: '1em',
    marginBottom: '1em',
    fontFamily: 'Roboto, "Helvetica Neue", sans-serif',
    fontSize: '16px',
    backgroundColor: '#fff',
    boxShadow: '2px 2px 3px 3px rgba(0,0,0,0.4)',
    display: 'inline-block',
    position: 'relative',
    textAlign: 'left',
  },
};
