export default {
  wrap: {
    outer: {
      display: 'table',
      position: 'fixed',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      minWidth: '1vw',
      minHeight: '1vh',
      backgroundColor: 'rgba(0,0,0,0.5)',
      overflow: 'hidden',
    },
    inner: {
      display: 'table-cell',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      align: 'center',
      verticalAlign: 'middle',
    },
    inner2: {
      position: 'relative',
      width: '100%',
      maxHeight: '100%',
      display: 'inline-block',
      overflow: 'auto',
      textAlign: 'center',
    },
  },
  choose: {
    marginTop: '2em',
    marginBottom: '2em',
    fontFamily: 'Roboto, "Helvetica Neue", sans-serif',
    fontSize: '16px',
    backgroundColor: '#fff',
    boxShadow: '2px 2px 3px 3px rgba(0,0,0,0.4)',
    display: 'inline-block',
    position: 'relative',
    textAlign: 'left',
  },
};
